# Generated by Django 2.1.8 on 2019-05-30 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MentorsBuildingTrainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors_with_trainings', to='interactions.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsFollowingTrainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('first_access', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_with_trainings', to='interactions.Student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_per_student', to='trainings.Training')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='trainings',
            field=models.ManyToManyField(related_name='students', through='interactions.StudentsFollowingTrainings', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsbuildingtrainings',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_per_mentors', to='interactions.Role'),
        ),
        migrations.AddField(
            model_name='mentorsbuildingtrainings',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_per_mentors', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='roles',
            field=models.ManyToManyField(related_name='mentors', through='interactions.MentorsBuildingTrainings', to='interactions.Role'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='trainings',
            field=models.ManyToManyField(related_name='mentors', through='interactions.MentorsBuildingTrainings', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='mentors',
            field=models.ManyToManyField(related_name='groups', to='interactions.Mentor'),
        ),
    ]
