# Generated by Django 2.1.8 on 2019-07-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url_content_readonly', models.URLField()),
                ('url_content_modification_allowed', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentsInChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_number', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_with_contents', to='trainings.Chapter')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_per_chapters', to='content.Content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='chapters',
            field=models.ManyToManyField(related_name='contents', through='content.ContentsInChapters', to='trainings.Chapter'),
        ),
        migrations.AddField(
            model_name='content',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_related', to='interactions.Group'),
        ),
    ]
