# Generated by Django 2.1.8 on 2019-07-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='group',
        ),
        migrations.AddField(
            model_name='content',
            name='groups',
            field=models.ManyToManyField(related_name='contents', to='interactions.Group'),
        ),
        migrations.AddField(
            model_name='content',
            name='mentor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='interactions.Mentor'),
            preserve_default=False,
        ),
    ]
